FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install 


FROM gcr.io/distroless/nodejs24-debian13
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY volumes1.js ./
COPY package.json ./
EXPOSE 8080
USER 65532
CMD ["volumes1.js" , "dev1"]
