name: Docker Build and Push

inputs:
 username:
  description: Docker Hub Login
  required: true
 password:
  description: Docker Hub Password
  required: true


runs:
  using: "composite"

steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
           username: ${{ inputs.username }}
           password: ${{ inputs.password }}
      - name: Build Docker Image
        shell: bash
        run: docker build -f dockerfile.multistage.distroless -t testdoceker-distroless .

      - name: Verify Docker login
        shell: bash
        run: |
         cat ~/.docker/config.json

      - name: Tag and Push  Docker image
        shell: bash
        run: |
         SHORT_SHA=${GITHUB_SHA::7}
         docker tag testdoceker-distroless ${{vars.DOCKERHUB_USERNAME}}/nodeapp-test:$SHORT_SHA
         docker push ${{vars.DOCKERHUB_USERNAME}}/nodeapp-test:$SHORT_SHA
