name: Docker CI

on: 
 workflow_dispatch: 

jobs:
  docker:
   runs-on: [self-hosted,siva_runner]
   steps:
     - name: Checkout Code
       uses: actions/checkout@v7
       with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build Docker Image
       run: docker run -f dockerfile.multistage.distroless -t testdoceker-distroless

     - name: Tag and Push  Docker image
       run: |
        SHORT_SHA=${GITHUB_SHA::7}
        docker tag testdoceker-distroless ${{vars.DOCKERHUB_USERNAME}}/nodeapp-test:$SHORT_SHA
        docker push ${{vars.DOCKERHUB_USERNAME}}/nodeapp-test:$SHORT_SHA
       
 
