 name: Node Basic Pipleline

 on:
  workflow_dispatch:
   inputs:
     environment:
      description: "Choose environment to run"
      required: true
      default: "dev"
      type: choice
      options:
        - dev
        - prod
     port:
      description: "Choose the Port"
      required: true
      default: "8080"
      type: choice
      options:
        - 8080
        - 5000
    

 jobs:
  Node:
   runs-on: [self-hosted, siva_runner]

   steps:
    - name: Checkout code 
      uses: actions/checkout@v7
    
    - name: Setup node
      uses: actions/setup-node@v7
      with:
       node-version: 24

    - name: Install Dependencies
      run: npm install

    - name: Create env file
      run: |
        echo "APP=${{ vars.DEV_APP}}" >> .env.dev1
        echo "PORT=${{ vars.DEV_PORT}}" >> .env.dev1
        echo "APP=${{ vars.PROD_APP}}" >> .env.prod
        echo "PORT=${{ vars.PROD_PORT}}" >> .env.prod 

    - name: Run Node application
      run: |
       node volumes1.js prod &
       sleep 5
       curl http://localhost:5000
       curl http://localhost:5000/health
       pkill -f 'node volumes1.js'
      
  
     
    
   
