name: Sample Pipleline

on:
 push: 
  branches: ["main"]

jobs:
  build:
   runs-on: [self-hosted, siva_runner]

   steps:
     - name: Build Step
       run: echo "Build Pipeline"

  Deploy:
   runs-on: [self-hosted, siva_runner]

   steps:
     - name: Deploy Step
       run: echo "Deploy Pipeline"
